#!/bin/sh

# Copyright © 2010 by Paweł Zuzelski <pawelz@pld-linux.org>
# Author: Paweł Zuzelski <pawelz@pld-linux.org>

# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See http://sam.zoy.org/wtfpl/COPYING for more
# details.

ROOTRELPATH=$(pwd | sed 's/[^/]\+/../g')/
ROOTRELPATH=${ROOTRELPATH#/}
ROOTRELPATH=${ROOTRELPATH#/}
export GIT_DIR=/var/lib/cg
export GIT_WORK_TREE="/"
export GIT_CEILING_DIRECTORIES=/tmp:/var/spool:/var/cache:/home

# opt parsing
while [ "$1" == "-${1#-}" ]; do
	GITOPTS="$GITOPTS $1"
	shift
done

GITCOMMAND="$1"
shift

while [ "$1" ]; do
	O=${1#/}
	[ "$O" != "$1" ] && O=$ROOTRELPATH$O
	GITCMDOPTS="$GITCMDOPTS $O"
	shift
done

exec git $GITOPTS $GITCOMMAND $GITCMDOPTS
